swagger: '2.0'
info:
  version: '1.0'
  title: BANKA
  description: Banka is a light-weight core banking application that powers banking operations like account creation, customer deposit and withdrawals. This app is meant to support a single bank, where users can signup and create bank accounts online, but must visit the branch to withdraw or deposit money..
  contact: {}
host: bankaapplication.herokuapp.com
basePath: /api/v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /auth/signin:
    post:
      description: Users can login to their BANKA Account
      summary: signin
      tags:
      - Auth
      operationId: AuthSigninPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/signinRequest'
      responses:
        200:
          description: ''
          headers: {}
  /auth/signup:
    post:
      description: Allows users to signup and create an account
      summary: signup
      tags:
      - Auth
      operationId: AuthSignupPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/signupRequest'
      responses:
        200:
          description: ''
          headers: {}
  /accounts:
    post:
      description: Authorized Users can create a bank account
      summary: Create Bank Account
      tags:
      - Accounts
      operationId: AccountsPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: token
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreateBankAccountRequest'
      responses:
        200:
          description: ''
          headers: {}
    get:
      description: Admin and staff can get all bank accounts
      summary: Get All Bank Accounts
      tags:
      - Accounts
      operationId: AccountsGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /accounts/999:
    get:
      description: Admin,staff or Authourized user can get a specific bank account details
      summary: Get Specific Bank Account
      tags:
      - Accounts
      operationId: Accounts999Get
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
    patch:
      description: Admin and staff can activate a bank account
      summary: Activate Bank Account
      tags:
      - Accounts
      operationId: Accounts999Patch
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: token
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/ActivateBankAccountRequest'
      responses:
        200:
          description: ''
          headers: {}
  /accounts/1699:
    delete:
      description: Admin and staff can delete a bank account
      summary: Delete Bank Account
      tags:
      - Accounts
      operationId: Accounts1699Delete
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /accounts/1099:
    patch:
      description: Admin and staff can deactivate a bank account
      summary: Deactivate Bank Account
      tags:
      - Accounts
      operationId: Accounts1099Patch
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: token
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/DeactivateBankAccountRequest'
      responses:
        200:
          description: ''
          headers: {}
  /user/idowuadeleke@gmail.com/accounts:
    get:
      description: Admin and staff can get a specific user bank account
      summary: Get a User Bank Account
      tags:
      - Accounts
      operationId: UserIdowuadelekeGmailComAccountsGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /transactions/1099/credit:
    post:
      description: staff(cashier) can credit a bank account
      summary: Credit Bank Account
      tags:
      - Transactions
      operationId: Transactions1099CreditPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: token
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreditBankAccountRequest'
      responses:
        200:
          description: ''
          headers: {}
  /transactions/1099/debit:
    post:
      description: Staff cashier can debit a bank account
      summary: Debit Bank Account
      tags:
      - Transactions
      operationId: Transactions1099DebitPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: token
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/DebitBankAccountRequest'
      responses:
        200:
          description: ''
          headers: {}
  /transactions/1:
    get:
      description: Admin and staff can get a specific account transaction detail
      summary: Get a Specific Transaction Detail
      tags:
      - Transactions
      operationId: Transactions1Get
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /accounts/999/transactions:
    get:
      description: Admin and staff can get a bank account transaction history
      summary: Get Account Transaction History
      tags:
      - Transactions
      operationId: Accounts999TransactionsGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
definitions:
  signinRequest:
    title: signinRequest
    example:
      email: goo2dness@gmail.com
      password: dele1989
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
  signupRequest:
    title: signupRequest
    example:
      firstname: Goodness
      lastname: Greatness
      email: gos829dness@gmail.com
      password: dele1989
      type: client
      isAdmin: false
    type: object
    properties:
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      password:
        type: string
      type:
        type: string
      isAdmin:
        type: boolean
    required:
    - firstname
    - lastname
    - email
    - password
    - type
    - isAdmin
  CreateBankAccountRequest:
    title: CreateBankAccountRequest
    example:
      type: savings
      balance: 400
    type: object
    properties:
      type:
        type: string
      balance:
        type: integer
        format: int32
    required:
    - type
    - balance
  ActivateBankAccountRequest:
    title: ActivateBankAccountRequest
    example:
      status: active
    type: object
    properties:
      status:
        type: string
    required:
    - status
  DeactivateBankAccountRequest:
    title: DeactivateBankAccountRequest
    example:
      status: dormant
    type: object
    properties:
      status:
        type: string
    required:
    - status
  CreditBankAccountRequest:
    title: CreditBankAccountRequest
    example:
      amount: 200
    type: object
    properties:
      amount:
        type: integer
        format: int32
    required:
    - amount
  DebitBankAccountRequest:
    title: DebitBankAccountRequest
    example:
      amount: 20.05
    type: object
    properties:
      amount:
        type: number
        format: double
    required:
    - amount
tags:
- name: Auth
- name: Accounts
- name: Transactions
